name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -q pytest pyyaml

      - name: Run unit tests
        run: python -m pytest -q

      # Lightweight smoke checks on tiny dev sets
      - name: Smoke check (EN, fast-cue gate)
        env:
          PRAGACT_FAST_CUES: "1"
          PRAGACT_FAST_TAU: "0.30"
        run: |
          python -m scripts.eval_confusion --config configs/default_en.yaml --data data/dev/dev_en.jsonl

      - name: Smoke check (ZH, fast-cue gate)
        env:
          PRAGACT_FAST_CUES: "1"
          PRAGACT_FAST_TAU: "0.20"
        run: |
          python -m scripts.eval_confusion --config configs/default_zh.yaml --data data/dev/dev_zh.jsonl
